apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-app-config
data:
  MONGOURL: "mongodb+srv://bahirk880:P9CeRRMwJqj1LNpx@cluster0.woxq2nz.mongodb.net/firstProject?retryWrites=true&w=majority"
