apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30000
